<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            // قهوة مختصة
            [
                'name' => 'قهوة إثيوبية مختصة',
                'slug' => 'ethiopian-specialty-coffee',
                'description' => 'قهوة إثيوبية مختصة بحبوب محمصة حديثاً مع نكهة الفاكهة الطبيعية',
                'price' => 35.00,
                'category' => 'قهوة مختصة',
                'category_id' => 1,
                'type' => 'regular',
                'calories' => 5,
                'walking_time' => 1,
                'preparation_time' => 8,
                'start_date' => null,
                'end_date' => null,
                'stock_quantity' => 50,
                'order_count' => 127,
                'is_available' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'كولد برو كولومبي',
                'slug' => 'colombian-cold-brew',
                'description' => 'قهوة كولد برو من حبوب كولومبية مميزة مع نعومة استثنائية',
                'price' => 28.00,
                'category' => 'قهوة مختصة',
                'category_id' => 1,
                'type' => 'regular',
                'calories' => 8,
                'walking_time' => 2,
                'preparation_time' => 5,
                'start_date' => null,
                'end_date' => null,
                'stock_quantity' => 40,
                'order_count' => 89,
                'is_available' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'قهوة جمايكية أسبوعية',
                'slug' => 'weekly-jamaican-coffee',
                'description' => 'قهوة جمايكية نادرة متوفرة لفترة محدودة فقط',
                'price' => 45.00,
                'category' => 'قهوة مختصة',
                'category_id' => 1,
                'type' => 'weekly',
                'calories' => 6,
                'walking_time' => 1,
                'preparation_time' => 10,
                'start_date' => '2025-08-26',
                'end_date' => '2025-09-02',
                'stock_quantity' => 25,
                'order_count' => 34,
                'is_available' => true,
                'is_featured' => true,
            ],

            // مشروبات ساخنة
            [
                'name' => 'لاتيه بالفانيليا',
                'slug' => 'vanilla-latte',
                'description' => 'لاتيه كريمي مع شراب الفانيليا الطبيعي وحليب مبخر',
                'price' => 22.00,
                'category' => 'مشروبات ساخنة',
                'category_id' => 2,
                'type' => 'regular',
                'calories' => 180,
                'walking_time' => 18,
                'preparation_time' => 5,
                'start_date' => null,
                'end_date' => null,
                'stock_quantity' => 100,
                'order_count' => 156,
                'is_available' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'كابتشينو إيطالي',
                'slug' => 'italian-cappuccino',
                'description' => 'كابتشينو إيطالي تقليدي مع رغوة الحليب المثالية',
                'price' => 18.00,
                'category' => 'مشروبات ساخنة',
                'category_id' => 2,
                'type' => 'regular',
                'calories' => 120,
                'walking_time' => 12,
                'preparation_time' => 4,
                'start_date' => null,
                'end_date' => null,
                'stock_quantity' => 80,
                'order_count' => 203,
                'is_available' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'شاي مساي التوابل',
                'slug' => 'spiced-masala-chai',
                'description' => 'شاي مساي هندي بالتوابل العطرية والحليب',
                'price' => 16.00,
                'category' => 'مشروبات ساخنة',
                'category_id' => 2,
                'type' => 'regular',
                'calories' => 90,
                'walking_time' => 9,
                'preparation_time' => 6,
                'start_date' => null,
                'end_date' => null,
                'stock_quantity' => 60,
                'order_count' => 78,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'شوكولاتة ساخنة أسبوعية',
                'slug' => 'weekly-hot-chocolate',
                'description' => 'شوكولاتة ساخنة فاخرة بالكريمة والمارشميلو',
                'price' => 25.00,
                'category' => 'مشروبات ساخنة',
                'category_id' => 2,
                'type' => 'weekly',
                'calories' => 320,
                'walking_time' => 32,
                'preparation_time' => 7,
                'start_date' => '2025-08-26',
                'end_date' => '2025-09-02',
                'stock_quantity' => 30,
                'order_count' => 45,
                'is_available' => true,
                'is_featured' => true,
            ],

            // مشروبات باردة
            [
                'name' => 'فرابيه الكراميل',
                'slug' => 'caramel-frappe',
                'description' => 'فرابيه بارد مع شراب الكراميل والكريمة المخفوقة',
                'price' => 24.00,
                'category' => 'مشروبات باردة',
                'category_id' => 3,
                'type' => 'regular',
                'calories' => 280,
                'walking_time' => 28,
                'preparation_time' => 3,
                'start_date' => null,
                'end_date' => null,
                'stock_quantity' => 70,
                'order_count' => 134,
                'is_available' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'عصير ليمونادة طازج',
                'slug' => 'fresh-lemonade',
                'description' => 'ليمونادة طازجة مع النعناع والثلج المجروش',
                'price' => 14.00,
                'category' => 'مشروبات باردة',
                'category_id' => 3,
                'type' => 'regular',
                'calories' => 110,
                'walking_time' => 11,
                'preparation_time' => 3,
                'start_date' => null,
                'end_date' => null,
                'stock_quantity' => 90,
                'order_count' => 167,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'سموثي الفراولة الأسبوعي',
                'slug' => 'weekly-strawberry-smoothie',
                'description' => 'سموثي الفراولة الطازجة مع الزبادي والعسل',
                'price' => 20.00,
                'category' => 'مشروبات باردة',
                'category_id' => 3,
                'type' => 'weekly',
                'calories' => 185,
                'walking_time' => 19,
                'preparation_time' => 4,
                'start_date' => '2025-08-26',
                'end_date' => '2025-09-02',
                'stock_quantity' => 35,
                'order_count' => 67,
                'is_available' => true,
                'is_featured' => true,
            ],

            // حلويات شرقية
            [
                'name' => 'كنافة نابلسية',
                'slug' => 'nablus-knafeh',
                'description' => 'كنافة نابلسية أصيلة بالجبن والقطر الطبيعي',
                'price' => 35.00,
                'category' => 'حلويات شرقية',
                'category_id' => 4,
                'type' => 'regular',
                'calories' => 420,
                'walking_time' => 42,
                'preparation_time' => 25,
                'start_date' => null,
                'end_date' => null,
                'stock_quantity' => 25,
                'order_count' => 89,
                'is_available' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'بقلاوة مشكلة',
                'slug' => 'mixed-baklava',
                'description' => 'بقلاوة مشكلة بالفستق واللوز والجوز',
                'price' => 28.00,
                'category' => 'حلويات شرقية',
                'category_id' => 4,
                'type' => 'regular',
                'calories' => 380,
                'walking_time' => 38,
                'preparation_time' => 20,
                'start_date' => null,
                'end_date' => null,
                'stock_quantity' => 40,
                'order_count' => 112,
                'is_available' => true,
                'is_featured' => false,
            ],

            // حلويات غربية
            [
                'name' => 'تيراميسو إيطالي',
                'slug' => 'italian-tiramisu',
                'description' => 'تيراميسو إيطالي كلاسيكي مع القهوة والماسكاربوني',
                'price' => 32.00,
                'category' => 'حلويات غربية',
                'category_id' => 5,
                'type' => 'regular',
                'calories' => 350,
                'walking_time' => 35,
                'preparation_time' => 15,
                'start_date' => null,
                'end_date' => null,
                'stock_quantity' => 20,
                'order_count' => 76,
                'is_available' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'تشيز كيك النيويورك',
                'slug' => 'new-york-cheesecake',
                'description' => 'تشيز كيك نيويورك الكلاسيكي مع صوص التوت',
                'price' => 38.00,
                'category' => 'حلويات غربية',
                'category_id' => 5,
                'type' => 'regular',
                'calories' => 480,
                'walking_time' => 48,
                'preparation_time' => 10,
                'start_date' => null,
                'end_date' => null,
                'stock_quantity' => 15,
                'order_count' => 94,
                'is_available' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'براونيز الشوكولاتة الأسبوعي',
                'slug' => 'weekly-chocolate-brownies',
                'description' => 'براونيز الشوكولاتة الداكنة مع الجوز المحمص',
                'price' => 26.00,
                'category' => 'حلويات غربية',
                'category_id' => 5,
                'type' => 'weekly',
                'calories' => 390,
                'walking_time' => 39,
                'preparation_time' => 12,
                'start_date' => '2025-08-26',
                'end_date' => '2025-09-02',
                'stock_quantity' => 20,
                'order_count' => 52,
                'is_available' => true,
                'is_featured' => true,
            ],

            // معجنات وفطائر
            [
                'name' => 'كروسان بالزبدة',
                'slug' => 'butter-croissant',
                'description' => 'كروسان فرنسي طازج بالزبدة الطبيعية',
                'price' => 15.00,
                'category' => 'معجنات وفطائر',
                'category_id' => 6,
                'type' => 'regular',
                'calories' => 240,
                'walking_time' => 24,
                'preparation_time' => 8,
                'start_date' => null,
                'end_date' => null,
                'stock_quantity' => 60,
                'order_count' => 145,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'مافن بالتوت الأزرق',
                'slug' => 'blueberry-muffin',
                'description' => 'مافن طري مليء بالتوت الأزرق الطازج',
                'price' => 18.00,
                'category' => 'معجنات وفطائر',
                'category_id' => 6,
                'type' => 'regular',
                'calories' => 280,
                'walking_time' => 28,
                'preparation_time' => 10,
                'start_date' => null,
                'end_date' => null,
                'stock_quantity' => 45,
                'order_count' => 98,
                'is_available' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'فطيرة السبانخ الأسبوعية',
                'slug' => 'weekly-spinach-pie',
                'description' => 'فطيرة السبانخ بالعجينة الرقيقة والجبن الطازج',
                'price' => 22.00,
                'category' => 'معجنات وفطائر',
                'category_id' => 6,
                'type' => 'weekly',
                'calories' => 320,
                'walking_time' => 32,
                'preparation_time' => 15,
                'start_date' => '2025-08-26',
                'end_date' => '2025-09-02',
                'stock_quantity' => 30,
                'order_count' => 43,
                'is_available' => true,
                'is_featured' => false,
            ],

            // وجبات خفيفة
            [
                'name' => 'ساندويش الأفوكادو',
                'slug' => 'avocado-sandwich',
                'description' => 'ساندويش الأفوكادو الطازج مع الطماطم والجرجير',
                'price' => 28.00,
                'category' => 'وجبات خفيفة',
                'category_id' => 7,
                'type' => 'regular',
                'calories' => 340,
                'walking_time' => 34,
                'preparation_time' => 8,
                'start_date' => null,
                'end_date' => null,
                'stock_quantity' => 35,
                'order_count' => 87,
                'is_available' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'سلطة الكينوا',
                'slug' => 'quinoa-salad',
                'description' => 'سلطة الكينوا مع الخضار الطازجة وصوص الليمون',
                'price' => 25.00,
                'category' => 'وجبات خفيفة',
                'category_id' => 7,
                'type' => 'regular',
                'calories' => 220,
                'walking_time' => 22,
                'preparation_time' => 12,
                'start_date' => null,
                'end_date' => null,
                'stock_quantity' => 30,
                'order_count' => 65,
                'is_available' => true,
                'is_featured' => false,
            ],

            // مثلجات
            [
                'name' => 'آيس كريم الفانيليا',
                'slug' => 'vanilla-ice-cream',
                'description' => 'آيس كريم الفانيليا الطبيعية مع قطع الفانيليا',
                'price' => 16.00,
                'category' => 'مثلجات',
                'category_id' => 8,
                'type' => 'regular',
                'calories' => 250,
                'walking_time' => 25,
                'preparation_time' => 3,
                'start_date' => null,
                'end_date' => null,
                'stock_quantity' => 80,
                'order_count' => 198,
                'is_available' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'ميلك شيك الفراولة الأسبوعي',
                'slug' => 'weekly-strawberry-milkshake',
                'description' => 'ميلك شيك الفراولة الكثيف مع الكريمة المخفوقة',
                'price' => 22.00,
                'category' => 'مثلجات',
                'category_id' => 8,
                'type' => 'weekly',
                'calories' => 380,
                'walking_time' => 38,
                'preparation_time' => 5,
                'start_date' => '2025-08-26',
                'end_date' => '2025-09-02',
                'stock_quantity' => 25,
                'order_count' => 72,
                'is_available' => true,
                'is_featured' => true,
            ],

            // منتجات نفدت للاختبار
            [
                'name' => 'قهوة البرازيل المحدودة',
                'slug' => 'limited-brazil-coffee',
                'description' => 'قهوة برازيلية محدودة الإنتاج من مزرعة خاصة',
                'price' => 50.00,
                'category' => 'قهوة مختصة',
                'category_id' => 1,
                'type' => 'regular',
                'calories' => 8,
                'walking_time' => 2,
                'preparation_time' => 12,
                'start_date' => null,
                'end_date' => null,
                'stock_quantity' => 0, // نفدت الكمية
                'order_count' => 234,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'كيك الليمون المنتهي',
                'slug' => 'expired-lemon-cake',
                'description' => 'كيك الليمون الطازج بكريمة الليمون الطبيعية',
                'price' => 30.00,
                'category' => 'حلويات غربية',
                'category_id' => 5,
                'type' => 'weekly',
                'calories' => 320,
                'walking_time' => 32,
                'preparation_time' => 18,
                'start_date' => '2025-08-19',
                'end_date' => '2025-08-25', // انتهت صلاحيته
                'stock_quantity' => 10,
                'order_count' => 78,
                'is_available' => true,
                'is_featured' => false,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
